# Adwaita-dark

[mgr]
cwd = { fg = "#deddda", italic = true }
hovered = { bg = "#2e2e32" }
preview_hovered = { bg = "#2e2e32" }
find_keyword = { fg = "#1d1d20", bg = "#ff9c5b", bold = true }
find_position = { fg = "#1d1d20", bg = "#7bdff4", bold = true }
marker_copied = { fg = "#57e389", bg = "#57e389" }
marker_cut = { fg = "#f66151", bg = "#f66151" }
marker_marked = { fg = "#c061cb", bg = "#c061cb" }
marker_selected = { fg = "#62a0ea", bg = "#62a0ea" }
count_copied = { fg = "#1d1d20", bg = "#57e389" }
count_cut = { fg = "#1d1d20", bg = "#ed333b" }
count_selected = { fg = "#1d1d20", bg = "#3584e4" }
border_symbol = "│"
border_style = { fg = "#5e5c64" }

[tabs]
active = { fg = "#ffffff", bg = "#3584e4" }
inactive = { fg = "#81d0ff", bg = "#2e2e32" }

[mode]
normal_main = { fg = "#ffffff", bg = "#3584e4", bold = true }
normal_alt = { fg = "#81d0ff", bg = "#2e2e32" }
select_main = { fg = "#ffffff", bg = "#9141ac", bold = true }
select_alt = { fg = "#fba7ff", bg = "#2e2e32" }

[status]
overall = { fg = "#deddda", bg = "#1d1d20" }
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#62a0ea", bg = "#2e2e32" }
progress_error = { fg = "#ff938c", bg = "#2e2e32" }
perm_type = { fg = "#81d0ff" }
perm_read = { fg = "#ffc057" }
perm_write = { fg = "#ff888c" }
perm_exec = { fg = "#8de698" }
perm_sep = { fg = "#5e5c64" }

[pick]
border = { fg = "#5e5c64" }
active = { fg = "#ffffff", bg = "#36363a" }
inactive = { fg = "#deddda" }

[input]
border = { fg = "#81d0ff" }
title = { fg = "#81d0ff" }
value = { fg = "#fba7ff" }
selected = { bg = "#36363a" }

[cmp]
border = { fg = "#81d0ff" }
active = { fg = "#ffffff", bg = "#36363a" }
inactive = { fg = "#deddda" }

[tasks]
border = { fg = "#5e5c64" }
title = { fg = "#81d0ff" }
hovered = { fg = "#ffffff", bg = "#36363a" }

[which]
cols = 3
mask = { bg = "#1d1d20" }
cand = { fg = "#7bdff4" }
rest = { fg = "#81d0ff" }
desc = { fg = "#fba7ff" }
separator = " ➜ "
separator_style = { fg = "#9a9996" }

[confirm]
border = { fg = "#5e5c64" }
title = { fg = "#81d0ff" }
btn_yes = { bg = "#36363a" }
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[spot]
border = { fg = "#5e5c64" }
title = { fg = "#81d0ff" }

[notify]
title_info = { fg = "#7bdff4" }
title_warn = { fg = "#ffc057" }
title_error = { fg = "#ff888c" }

[help]
on = { fg = "#8de698" }
run = { fg = "#fba7ff" }
desc = { fg = "#7bdff4" }
hovered = { bg = "#2e2e32" }
footer = { fg = "#deddda", bg = "#222226" }

[filetype]
rules = [
  { mime = "image/*", fg = "#ffc057" },
  { mime = "{audio,video}/*", fg = "#fba7ff" },
  { mime = "application/*zip", fg = "#ff888c" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ff888c" },
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7bdff4" },
  { url = "*", is = "orphan", bg = "#c01c28" },
  { url = "*", is = "exec", fg = "#8de698" },
  { url = "*/", fg = "#81d0ff" },
  { url = "*", fg = "#deddda" }
]
