# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return ;;
esac

# if ~/bin exists, add it to path
if [ -x $HOME/bin ]; then
  PATH=$PATH:$HOME/bin
fi

# if ~/.local/bin exists, add it to path
if [ -x $HOME/.local/bin ]; then
  PATH=$PATH:$HOME/.local/bin
fi

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# Set Standard Editor
export EDITOR=nvim

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
xterm | xterm-color | *-256color) color_prompt=yes ;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
  if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.)
    color_prompt=yes
  else
    color_prompt=
  fi
fi

if [ "$color_prompt" = yes ]; then
  if [[ ${EUID} == 0 ]]; then
    PS1="\n\[\033[0;31m\][\t]\[\033[0;73m\]\[\033[0;36m\] [\[\033[1;32m\]\u\[\033[0;33m\]@\[\033[1;34m\]\h:\[\033[0;35m\] \w \[\033[0;36m\]]\[\033[0;31m\]\\n\[\033[0;37m\]\$\[\033[0;37m\] "
  else
    PS1="\n\[\033[0;31m\][\t]\[\033[0;36m\] [\[\033[1;32m\]\u\[\033[0;33m\]@\[\033[1;34m\]\h:\[\033[0;35m\] \w \[\033[0;36m\]]\[\033[0;31m\]\\n\[\033[0;37m\]\$\[\033[0;37m\] "
  fi
else
  PS1="${debian_chroot:+($debian_chroot)}\u@\h \w \$ "
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm* | rxvt*)
  PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h \w\a\]$PS1"
  ;;
*) ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'

  # Make grep colorful
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# exa colors
export EXA_COLORS="da=1;35"
# exa aliases
alias ls="eza --git"
alias l="eza -l --git"
alias a="eza -a --git"
alias la="eza -la --git"

# SUDO
alias _="sudo "

# neovim
alias vim="nvim"
alias vi="nvim"
alias v="nvim"

# ShellCheck alias
alias sc="/usr/bin/shellcheck -s sh -o all"

# shortcuts
alias rr="ranger"

# get IPv4 and IPv6
alias ipaddr='echo -n "IPv4: "; curl -s -4 https://my.ip.fi; echo -n "IPv6: "; curl -s -6 https://my.ip.fi'

# other aliases
alias todo="todo.sh" # Todo list
alias mcfly-tmp-rm="sudo rm /tmp/mcfly.*"

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# import local bashrc
if [ -f ~/.bashrc.local ]; then
  . ~/.bashrc.local
fi

# Enable STARSHIP prompt
which starship >/dev/null 2>&1 && eval "$(starship init bash)"

####################################
# Show Todo List on start of shell #
####################################
which todo.sh >/dev/null 2>&1 && todo ls

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
