# Adwaita-dark

foreground #ffffff
background #1d1d20

color0 #000000
color1 #ed333b
color2 #33d17a
color3 #f6d32d
color4 #3584e4
color5 #9141ac
color6 #2190a4
color7 #deddda

color8 #5e5c64
color9 #ff938c
color10 #78e9ab
color11 #ffc252
color12 #81d0ff
color13 #fba7ff
color14 #7bdff4
color15 #ffffff

font_family JetBrainsMono Nerd Font Mono
font_size 14.0

window_padding_width 0
window_margin_width 0
background_opacity 1.0

cursor_shape beam
cursor_blink_interval 0
cursor #ffffff
cursor_text_color #1d1d20

enable_audio_bell no
