fg: gopher://gopher.floodgap.com/1/v2/vs?{q}
gp: gemini://gemi.dev/cgi-bin/wp.cgi/search?{q}
gpde: gemini://gemi.dev/cgi-bin/wp.cgi/search/de?{q}
ken: gemini://kennedy.gemi.dev/search?{q}
tlgs: gemini://tlgs.one/search?{q}
