show_type_badges: true
type_badges:
  '0': '[TXT] '
  '1': '[DIR] '
  '2': '[UKN] '
  '3': '[ERR] '
  '4': '[BIN] '
  '5': '[BIN] '
  '6': '[BIN] '
  '7': '[INP] '
  '8': '[TEL] '
  '9': '[BIN] '
  I: '[IMG] '
  P: '[PDF] '
  X: '[XML] '
  d: '[DOC] '
  g: '[GIF] '
  h: '[URL] '
  i: '[IMG] '
  s: '[SND] '
  unknown: '[XXX] '
