client_certificate_used: ⚿
fingerspace_link: ☛
geminispace_link: ⪢
gopherspace_link: ○
list_item_bullet: •
nexspace_link: ☽
otherspace_link: ↗
spartanspace_link: ⪧
titanspace_link: ⩓
unverified: •
verified_ca: ⛉
verified_off: ✗
verified_tofu: ✓
