[FileDialog]
history=file:///home/daniel/Work/Programming/git.envs.net/envsbot/plugins, file:///home/daniel/Work/Programming/git.envs.net/envsbot, file:///home/daniel/Work, file:///home/daniel/Downloads, file:///home/daniel/Bilder/Screen
lastVisited=file:///home/daniel/Downloads
qtVersion=6.11.1
shortcuts=file:, file:///home/daniel
sidebarWidth=154
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3\x34\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\xa9\0\0\0\x1\0\0\0\0\0\0\0i\0\0\0\x1\0\0\0\0\0\0\0k\0\0\0\x1\0\0\0\0\0\0\0\xb7\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
