## Send prefix
set-option -g prefix C-a
unbind-key C-a
unbind-key k
unbind k
bind-key C-a send-prefix

## 0 is too far away for switching windows
set -g base-index 1

## Own config
# Use Alt-Arrow keys to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
# Shift-Arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

# set easier window split
bind-key h split-window -h
bind-key v split-window -v

# set zoom to C-y
bind -n C-y resize-pane -Z

# reload tmux config
bind-key r source-file ~/.config/tmux/tmux.conf

# Scan pane for urls
#bind-key C-u run 'tmux popup -E -b double -w 100% -h 100% \
                  sh -c "tmux capture-pane -Jp | urlscan --run \"echo {} | xclip -i\"'


# Other config
# set window activity to on
setw -g monitor-activity off
setw -g window-status-activity-style bg=red
#set -g visual-activity on
set -g mouse on

# Clipboard
set -s set-clipboard on
set -g allow-passthrough

# environment variables
set-environment -g color_prompt yes

# THEME
set -g default-terminal "tmux-256color"

## PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-urlscan'
set -g @urlscan-args '-E "(?:(?:http|https|gopher|gemini|finger|mailto):\/\/[^\s]+|[^\s]+@[^\s]+)" -c -d -r "echo {} | wl-copy"'
set -g @plugin 'jimeh/tmux-themepack'

## Initialize plugin manager
run -b '~/.config/tmux/plugins/tpm/tpm'

## Themes
set -g @themepack 'powerline/block/orange'

